import os
from pymongo import MongoClient

MONGO_DATABASE_NAME = os.environ.get("MONGO_DATABASE_NAME")
MONGO_DATABASE_USER = os.environ.get("MONGO_DATABASE_USER")
MONGO_DATABASE_PASSWORD = os.environ.get("MONGO_DATABASE_PASSWORD")
MONGO_DATABASE_CONTAINER_NAME = os.environ.get(
    "MONGO_DATABASE_CONTAINER_NAME")
MONGO_DATABASE_PORT = int(os.environ.get("MONGO_DATABASE_PORT"))

DATABASE_URL = "%s://%s:%s@%s:%d" % (
    MONGO_DATABASE_NAME, MONGO_DATABASE_USER, MONGO_DATABASE_PASSWORD, MONGO_DATABASE_CONTAINER_NAME, MONGO_DATABASE_PORT)

client = MongoClient(DATABASE_URL)
db = client.test_database  # DB名がtest_database
